baseURL: "vivek-kandimalla.github.io" 
title: Vivek Kandimalla
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: CV
          url: cv_vivek.pdf
        #   weight: 1
        # - name: Books
        #   url: books/
        #   weight: 2
        # - name: Papers
        #   url: papers/
        #   weight: 2
        # - name: Courses
        #   url: courses/
        #   weight: 3
        # - name: Data
        #   url: data/
        #   weight: 4 
        # - name: Blog
        #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #   weight: 5

params:
    description: "Website of Vivek Kandimalla"
    author: Vivek Kandimalla
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["CV"]
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Vivek Kandimalla
          subtitle: "Hello! I am fourth year PhD student in Economics at the Indian Institute of Management Bangalore.
          My research interests span across International Trade, Economic Geography and Macro Development."
          imageUrl: "IMG_20240625_141615-EDIT.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Vivek
          buttons:
                 - name: CV
                   url: cv_vivek.pdf
                #  - name: Books
                #    url: books/
                #  - name: Papers
                #    url: papers/
            # - name: Courses
            #   url: courses/
            # - name: Data
            #   url: data/
            # - name: Tags
            #   url: tags/
            # - name: Archive
            #   url: archive/
            # - name: Blog
            #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: Email
          url: mailto:saivivek.kandimalla21@iimb.ac.in 
        # - name: CV
        #   url: cv.pdf
        # - name: Google Scholar
        #   url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        # - name: Location
        #   url: location/
        # - name: Office Hours
        #   url: officehours/
        # - name: GitHub
        #   url: https://github.com/pmichaillat
        # - name: Substack
        #   url: https://pmichaillat.substack.com
        # - name: YouTube
        #   url: https://www.youtube.com/@alexandermccallsmithoffici9000
        - name: Twitter
          url: https://twitter.com/vivek_kandi
        - name: LinkedIn
          url: https://www.linkedin.com/in/vivek-kandimalla/
        - name: Blogger
          url: https://musingsofvivek.blogspot.com/

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Vivek"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
